### ISSUE TITLE
Provide descriptions

### ISSUE THREAD

**Issue by michelpereira** [ehsanghaffarii/awesome-clubhouse#2]
Line number:
58 - [Tech & Chill](https://www.clubhouse.com/club/techchill)
59 - [Startup Club](https://clubhousedb.com/club/45-startup-club)
60 - [Tech Talks](https://clubhousedb.com/club/3225-tech-talks)

265 - [Analyzing Clubhouse](https://blog.theori.io/research/korean/analyzing-clubhouse/)
269 - [Clubhouse Newsletter](https://www.clubhouse.com/newsletter)

276 - [Clubhouse](https://www.clubhouse.com/)
277 - [Clubhouse Api](https://clubhouseapi.com/)
278 - [Clubhouse-cli](https://github.com/ehsanghaffarii/clubhouse-cli)

**Comment by ehsanghaffar** [comment]
ok, Thank you for your attention and fixing that, I mergrd your pull request
