### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Kimozayed20** [ehsanghaffarii/awesome-clubhouse#5]
.

**Comment by ehsanghaffar** [comment]
Hi, 
Please describe your issue

**Comment by Kimozayed20** [comment]
I have a problem every time I enter the accounts the room by my tokens through your script after running the script the accounts come out after five minutes only

**Comment by Kimozayed20** [comment]
Is there a way to determine how long the accounts stay in the room by your code

**Comment by Kimozayed20** [comment]
the name of script is : join-room

**Comment by Kimozayed20** [comment]
#
# Join a room with a given room id and user auth token.
# Author: Ehsan Ghaffar
# This file is part of the spacepy.
import requests
import json


api_url = "https://www.clubhouseapi.com/api/"

token = "YOUR_TOKEN_HERE"

channel_id = ""


def join_room(t, url, ch):
    headers = {
        "CH-Languages": "en-US",
        "CH-Locale": "en_US",
        "Accept": "application/json",
        "Accept-Encoding": "gzip, deflate",
        "CH-AppBuild": "2576",
        "CH-AppVersion": "1.0.0",
        "CH-UserID": "<id>",
        "User-Agent": "clubhouse/490 (iPhone; iOS 14.4; Scale/2.00)",
        "Connection": "alive",
        "Content-Type": "application/json; charset=utf-8",
        "Authorization": "Token " + token
    }
    end_point = url + 'join_channel'

    payload = {
        "channel": ch
    }

    response = requests.request(
        "POST", end_point, json=payload, headers=headers)
    room_res = response.json()
    dumped_res = json.dumps(room_res, indent=2)
    print(room_res)


# call join rooom function
join_room(token, api_url, channel_id)

**Comment by Kimozayed20** [comment]
"???

**Comment by ehsanghaffar** [comment]
> "???

Soon ...

**Comment by Kimozayed20** [comment]
What do you mean by soon??
